import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { bigint, boolean, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { Pool } from "pg";

export * from "./principals.js";
export * from "./outbox.js";
export * from "./domain-event-outbox.js";
export * from "./run-submission.js";
export * from "./run-command-resolver.js";
export * from "./run-publication-finalizer.js";
export * from "./evidence-store.js";
export * from "./model-audit.js";
export * from "./memory-deletion-audit.js";
export * from "./run-checkpoints.js";
export * from "./migrations.js";

const id = () => uuid("id").primaryKey().$defaultFn(randomUUID);
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const organizations = pgTable("organizations", { id: id(), name: varchar("name", { length: 200 }).notNull(), createdAt: createdAt() });
export const users = pgTable("users", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), oidcSubject: varchar("oidc_subject", { length: 255 }).notNull(), email: varchar("email", { length: 320 }).notNull(), createdAt: createdAt() }, (table) => [index("users_organization_idx").on(table.organizationId)]);
export const conversations = pgTable("conversations", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), createdBy: uuid("created_by").notNull().references(() => users.id), title: varchar("title", { length: 140 }).notNull(), archivedAt: timestamp("archived_at", { withTimezone: true }), deletedAt: timestamp("deleted_at", { withTimezone: true }), deletedBy: uuid("deleted_by"), createdAt: createdAt(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("conversations_organization_idx").on(table.organizationId)]);
export const messages = pgTable("messages", { id: id(), conversationId: uuid("conversation_id").notNull().references(() => conversations.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), role: varchar("role", { length: 16 }).notNull(), content: text("content").notNull(), runId: uuid("run_id"), createdAt: createdAt() }, (table) => [index("messages_conversation_idx").on(table.organizationId, table.conversationId)]);
export const researchRuns = pgTable("research_runs", { id: id(), conversationId: uuid("conversation_id").notNull().references(() => conversations.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), status: varchar("status", { length: 20 }).notNull(), question: text("question").notNull(), budget: jsonb("budget").notNull(), state: jsonb("state").notNull(), createdAt: createdAt(), finishedAt: timestamp("finished_at", { withTimezone: true }) }, (table) => [index("research_runs_conversation_idx").on(table.conversationId), index("research_runs_paused_idx").on(table.organizationId, table.createdAt)]);
export const runEvents = pgTable("run_events", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), sequence: bigint("sequence", { mode: "number" }).notNull(), type: varchar("type", { length: 40 }).notNull(), payload: jsonb("payload").notNull(), createdAt: createdAt() }, (table) => [index("run_events_run_idx").on(table.organizationId, table.runId)]);
export const researchRunCheckpoints = pgTable("research_run_checkpoints", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), phase: varchar("phase", { length: 40 }).notNull(), snapshot: jsonb("snapshot").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [index("research_run_checkpoints_run_idx").on(table.runId, table.createdAt)]);
export const outboxEvents = pgTable("outbox_events", { id: id(), eventType: varchar("event_type", { length: 80 }).notNull(), aggregateId: uuid("aggregate_id").notNull(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), payload: jsonb("payload").notNull(), attempts: integer("attempts").notNull().default(0), occurredAt: createdAt(), lockedUntil: timestamp("locked_until", { withTimezone: true }), publishedAt: timestamp("published_at", { withTimezone: true }) }, (table) => [index("outbox_unpublished_idx").on(table.occurredAt)]);
export const domainEventOutbox = pgTable("domain_event_outbox", { id: id(), eventType: varchar("event_type", { length: 120 }).notNull(), aggregateId: uuid("aggregate_id").notNull(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), payload: jsonb("payload").notNull(), attempts: integer("attempts").notNull().default(0), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), lockedUntil: timestamp("locked_until", { withTimezone: true }), publishedAt: timestamp("published_at", { withTimezone: true }) }, (table) => [index("domain_event_outbox_unpublished_idx").on(table.occurredAt)]);
export const evidenceItems = pgTable("evidence_items", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), sourceType: varchar("source_type", { length: 40 }).notNull(), authority: varchar("authority", { length: 20 }).notNull(), sourceUrl: text("source_url"), locator: text("locator").notNull(), contentHash: varchar("content_hash", { length: 128 }).notNull(), content: text("content").notNull(), metadata: jsonb("metadata").notNull(), createdAt: createdAt() }, (table) => [index("evidence_run_idx").on(table.runId), index("evidence_tenant_hash_idx").on(table.organizationId, table.contentHash)]);
export const researchRunEvidence = pgTable("research_run_evidence", { runId: uuid("run_id").notNull().references(() => researchRuns.id), evidenceId: uuid("evidence_id").notNull().references(() => evidenceItems.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), createdAt: createdAt() }, (table) => [index("research_run_evidence_run_idx").on(table.runId), index("research_run_evidence_evidence_idx").on(table.evidenceId), index("research_run_evidence_organization_idx").on(table.organizationId, table.runId)]);
export const toolInvocations = pgTable("tool_invocations", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), toolId: varchar("tool_id", { length: 120 }).notNull(), idempotencyKey: varchar("idempotency_key", { length: 200 }).notNull(), invokedAt: timestamp("invoked_at", { withTimezone: true }).notNull(), ok: boolean("ok").notNull(), inputHash: varchar("input_hash", { length: 128 }).notNull(), outputHash: varchar("output_hash", { length: 128 }), evidenceIds: jsonb("evidence_ids").notNull(), estimatedCostUsd: numeric("estimated_cost_usd", { precision: 12, scale: 6 }).notNull(), durationMs: integer("duration_ms").notNull(), failureCode: varchar("failure_code", { length: 40 }) }, (table) => [index("tool_invocations_run_idx").on(table.runId, table.invokedAt), uniqueIndex("tool_invocations_run_idempotency_idx").on(table.runId, table.idempotencyKey)]);
export const modelInvocations = pgTable("model_invocations", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), modelId: varchar("model_id", { length: 255 }).notNull(), operation: varchar("operation", { length: 80 }).notNull(), invokedAt: timestamp("invoked_at", { withTimezone: true }).notNull(), inputTokens: integer("input_tokens").notNull(), outputTokens: integer("output_tokens").notNull(), totalTokens: integer("total_tokens").notNull(), estimatedCostUsd: numeric("estimated_cost_usd", { precision: 12, scale: 6 }) }, (table) => [index("model_invocations_run_idx").on(table.runId, table.invokedAt)]);
export const researchReports = pgTable("research_reports", { id: id(), runId: uuid("run_id").notNull().references(() => researchRuns.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), version: integer("version").notNull(), markdown: text("markdown").notNull(), citations: jsonb("citations").notNull(), createdAt: createdAt() }, (table) => [index("research_reports_organization_idx").on(table.organizationId, table.createdAt)]);
export const memoryRecords = pgTable("memory_records", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), userId: uuid("user_id").references(() => users.id), conversationId: uuid("conversation_id").references(() => conversations.id), scope: varchar("scope", { length: 20 }).notNull(), visibility: varchar("visibility", { length: 20 }).notNull(), content: text("content").notNull(), sourceRunId: uuid("source_run_id").references(() => researchRuns.id), expiresAt: timestamp("expires_at", { withTimezone: true }), retentionPolicy: varchar("retention_policy", { length: 32 }).notNull().default("organization_default"), metadata: jsonb("metadata").notNull(), preferenceKey: varchar("preference_key", { length: 64 }), createdAt: createdAt() }, (table) => [index("memory_scope_idx").on(table.organizationId, table.userId, table.scope), index("memory_conversation_idx").on(table.organizationId, table.conversationId, table.scope), uniqueIndex("memory_active_preference_idx").on(table.organizationId, table.userId, table.preferenceKey).where(sql`${table.preferenceKey} is not null`)]);
export const memoryDeletionAuditEvents = pgTable("memory_deletion_audit_events", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), memoryId: uuid("memory_id").notNull(), actorUserId: uuid("actor_user_id"), memoryScope: varchar("memory_scope", { length: 20 }).notNull(), sourceRunId: uuid("source_run_id"), evidenceIds: jsonb("evidence_ids").notNull(), eventType: varchar("event_type", { length: 16 }).notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull() }, (table) => [index("memory_deletion_audit_organization_idx").on(table.organizationId, table.occurredAt)]);

export function createDatabase(databaseUrl: string) {
  const pool = new Pool({ connectionString: databaseUrl, max: 10 });
  return { db: drizzle(pool), pool };
}
