import { z } from "zod";

export const EnvironmentSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  API_HOST: z.string().default("0.0.0.0"),
  API_PORT: z.coerce.number().int().positive().default(3001),
  CORS_ALLOWED_ORIGINS: z.string().default("http://localhost:3000"),
  DATABASE_URL: z.string().url().optional(),
  PERSISTENCE_MODE: z.enum(["memory", "postgres"]).default("memory"),
  REDIS_URL: z.string().url().optional(),
  REDIS_RUN_EVENT_STREAM_KEY: z.string().regex(/^[a-zA-Z0-9:_-]{1,160}$/).default("research:run-events:v1"),
  REDIS_RUN_EVENT_STREAM_MAX_LENGTH: z.coerce.number().int().min(1_000).max(100_000).default(20_000),
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: z.string().url().optional(),
  AWS_REGION: z.string().default("us-east-1"),
  SQS_RESEARCH_RUN_QUEUE_URL: z.string().url().optional(),
  SQS_RESEARCH_RUN_VISIBILITY_TIMEOUT_SECONDS: z.coerce.number().int().min(60).max(43_200).default(360),
  MAX_ACTIVE_RUNS_PER_USER: z.coerce.number().int().min(1).max(20).default(2),
  MAX_ACTIVE_RUNS_PER_ORGANIZATION: z.coerce.number().int().min(1).max(200).default(10),
  MEMORY_RETENTION_BATCH_SIZE: z.coerce.number().int().min(1).max(1_000).default(100),
  EVENTBRIDGE_EVENT_BUS_NAME: z.string().regex(/^[A-Za-z0-9._\/-]{1,256}$/).optional(),
  BEDROCK_MODEL_ID: z.string().min(1).optional(),
  BEDROCK_EMBEDDING_MODEL_ID: z.string().min(1).optional(),
  BEDROCK_INPUT_COST_PER_1K_USD: z.coerce.number().nonnegative().optional(),
  BEDROCK_OUTPUT_COST_PER_1K_USD: z.coerce.number().nonnegative().optional(),
  BEDROCK_EMBEDDING_INPUT_COST_PER_1K_USD: z.coerce.number().nonnegative().optional(),
  OPENSEARCH_ENDPOINT: z.string().url().optional(),
  OPENSEARCH_INDEX: z.string().regex(/^[a-z0-9][a-z0-9_-]{0,127}$/).optional(),
  EVIDENCE_S3_BUCKET: z.string().min(3).optional(),
  EVIDENCE_S3_PREFIX: z.string().default("evidence/"),
  REDSHIFT_WORKGROUP: z.string().min(1).optional(),
  REDSHIFT_DATABASE: z.string().min(1).optional(),
  REDSHIFT_SECRET_ARN: z.string().min(1).optional(),
  MARKET_DATA_LICENSE: z.string().min(1).optional(),
  NEO4J_URI: z.string().regex(/^neo4j(?:\+s|\+ssc)?:\/\//).optional(),
  NEO4J_USERNAME: z.string().min(1).optional(),
  NEO4J_PASSWORD: z.string().min(1).optional(),
  OIDC_ISSUER: z.string().url().optional(),
  OIDC_AUDIENCE: z.string().min(1).optional(),
  OIDC_ORGANIZATION_CLAIM: z.string().default("organization_id"),
  OIDC_ROLES_CLAIM: z.string().default("roles"),
  OIDC_ENTITLEMENTS_CLAIM: z.string().default("entitlements"),
  OIDC_EMAIL_CLAIM: z.string().default("email"),
  TOOL_MANIFEST_CATALOG_JSON: z.string().min(2).optional(),
  SEC_USER_AGENT: z.string().min(8).optional(),
  SEC_MAX_RESPONSE_BYTES: z.coerce.number().int().min(64 * 1024).max(5 * 1024 * 1024).default(5 * 1024 * 1024),
  SEC_INGEST_TICKERS: z.string().optional(),
  SEC_INGEST_TENANT_ID: z.string().uuid().optional(),
});

export type AppConfig = z.infer<typeof EnvironmentSchema>;
